### ISSUE TITLE
Startup error.

### ISSUE THREAD

**Issue by Zelaf** [Duke-Jones/ED-IBE#32]
I'm getting an error. Just installed the tool.

First one is:

```
17.04.2017 21:14:19 : ED-IBE v0.6.3.0
17.04.2017 21:14:19 : Unhandled Exception
--------------------------------------------------------------------------------
17.04.2017 21:14:19 : Error in retheming-function
17.04.2017 21:14:19 :    at IBE.Enums_and_Utility_Classes.Extensions_Control.Retheme(Control controlObject) in E:\dev\RN\ED-IBE\ED-IBE\Enums and Utility Classes\Extensions.cs:line 443
   at IBE.Enums_and_Utility_Classes.RNBaseForm.RNBaseForm_Load(Object sender, EventArgs e) in E:\dev\RN\ED-IBE\ED-IBE\Enums and Utility Classes\RNBaseForm.cs:line 138
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
--------------------------------------------------------------------------------
17.04.2017 21:14:19 : Object reference not set to an instance of an object.
17.04.2017 21:14:19 :    at IBE.Enums_and_Utility_Classes.Extensions_Control.Retheme(Control controlObject) in E:\dev\RN\ED-IBE\ED-IBE\Enums and Utility Classes\Extensions.cs:line 418

********************************************************************************
```
Clicking Ignore opens another one.

```
17.04.2017 21:14:19 : ED-IBE v0.6.3.0
17.04.2017 21:14:19 : Error while initializing the program object
--------------------------------------------------------------------------------
17.04.2017 21:14:19 : Fehler beim Verbinden, ConnectionString = <database=Elite_DB;server=localhost;Port=3306;user id=RN_User;Password=Elite;ConnectionTimeout=60;DefaultCommandTimeout=60;Keepalive=600;Allow User Variables=True;UseAffectedRows=True> (master)
17.04.2017 21:14:19 :    at IBE.SQL.DBConnector.Connect() in E:\dev\RN\ED-IBE\ED-IBE\SQL\DBConnector.cs:line 259
   at IBE.Program.Init() in E:\dev\RN\ED-IBE\ED-IBE\Program.cs:line 391
--------------------------------------------------------------------------------
17.04.2017 21:14:19 : Authentication to host 'localhost' for user 'RN_User' using method 'mysql_native_password' failed with message: Access denied for user 'RN_User'@'localhost' (using password: YES)
17.04.2017 21:14:19 :    at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at IBE.SQL.DBConnector.Connect() in E:\dev\RN\ED-IBE\ED-IBE\SQL\DBConnector.cs:line 251
--------------------------------------------------------------------------------
17.04.2017 21:14:19 : Access denied for user 'RN_User'@'localhost' (using password: YES)
17.04.2017 21:14:19 :    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()

********************************************************************************
```

Clicking ignore again opens yet another one.
```
17.04.2017 21:14:58 : ED-IBE v0.6.3.0
17.04.2017 21:14:58 : Unhandled Exception
--------------------------------------------------------------------------------
17.04.2017 21:14:58 : Error in retheming-function
17.04.2017 21:14:58 :    at IBE.Enums_and_Utility_Classes.Extensions_Control.Retheme(Control controlObject) in E:\dev\RN\ED-IBE\ED-IBE\Enums and Utility Classes\Extensions.cs:line 443
   at IBE.Enums_and_Utility_Classes.RNBaseForm.RNBaseForm_Load(Object sender, EventArgs e) in E:\dev\RN\ED-IBE\ED-IBE\Enums and Utility Classes\RNBaseForm.cs:line 138
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
--------------------------------------------------------------------------------
17.04.2017 21:14:58 : Object reference not set to an instance of an object.
17.04.2017 21:14:58 :    at IBE.Enums_and_Utility_Classes.Extensions_Control.Retheme(Control controlObject) in E:\dev\RN\ED-IBE\ED-IBE\Enums and Utility Classes\Extensions.cs:line 418

********************************************************************************
```

After clicking ignore on that one the main program window opens the loading window stays and the connect to sql server text doesn't change and does not become OK.

**Comment by Zelaf** [comment]
I successfully worked around it by closing ED Toolbox which also had a MYSQL service running and using MYSQL for it's database.
I made the PR #33 and hopefully it will be accepted or edited to fit into the text correctly.
