### ISSUE TITLE
Companion IO: no verified login credentials! ED Companion Interface (after beyond chapter 4 update) 

### ISSUE THREAD

**Issue by Jantik** [Duke-Jones/ED-IBE#42]
Get the following error when trying check/link IO

Error in CompanionDataView_Load
The remote server returned an error: (404) Not Found

23.12.2018 16:45:07 : ED-IBE v0.7.2.0
23.12.2018 16:45:07 : Error in CompanioDataView_Load
--------------------------------------------------------------------------------
23.12.2018 16:45:07 : Error while getting current state
23.12.2018 16:45:07 :    at IBE.IBECompanion.CompanioDataView.GetState() in E:\dev\RN\ED-IBE\ED-IBE\IBECompanion\CompanionDataView.cs:line 164
   at IBE.IBECompanion.CompanioDataView.CompanioDataView_Load(Object sender, EventArgs e) in E:\dev\RN\ED-IBE\ED-IBE\IBECompanion\CompanionDataView.cs:line 36
--------------------------------------------------------------------------------
23.12.2018 16:45:07 : Error while getting data from the servers
23.12.2018 16:45:07 :    at IBE.IBECompanion.CompanionData.GetProfileData(Boolean useCachedData) in E:\dev\RN\ED-IBE\ED-IBE\IBECompanion\CompanionData.cs:line 231
   at IBE.IBECompanion.CompanioDataView.GetState() in E:\dev\RN\ED-IBE\ED-IBE\IBECompanion\CompanionDataView.cs:line 68
--------------------------------------------------------------------------------
23.12.2018 16:45:07 : The remote server returned an error: (404) Not Found.
23.12.2018 16:45:07 :    at System.Net.HttpWebRequest.GetResponse()
   at EDCompanionAPI.HttpHelper.Get(String url, NameValueCollection query) in E:\dev\RN\ED-IBE\EDCompanionAPI\HttpHelper.cs:line 36
   at EDCompanionAPI.EliteCompanion.LoginInternal() in E:\dev\RN\ED-IBE\EDCompanionAPI\EliteCompanion.cs:line 145
   at EDCompanionAPI.EliteCompanion.GetProfileDataInternal(Boolean force) in E:\dev\RN\ED-IBE\EDCompanionAPI\EliteCompanion.cs:line 324
   at EDCompanionAPI.EliteCompanion.GetProfileData(Boolean force) in E:\dev\RN\ED-IBE\EDCompanionAPI\EliteCompanion.cs:line 304
   at IBE.IBECompanion.CompanionData.GetProfileData(Boolean useCachedData) in E:\dev\RN\ED-IBE\ED-IBE\IBECompanion\CompanionData.cs:line 198

********************************************************************************

**Comment by pricemtw** [comment]
I'm also getting this issue, any luck fixing this or a workaround of some sort? I tried googling around and looking for answers but can't find anyone else mentioning this.



13.01.2019 00:39:21 : ED-IBE v0.7.2.0
13.01.2019 00:39:21 : Error in CompanioDataView_Load
--------------------------------------------------------------------------------
13.01.2019 00:39:21 : Error while getting current state
13.01.2019 00:39:21 :    at IBE.IBECompanion.CompanioDataView.GetState() in E:\dev\RN\ED-IBE\ED-IBE\IBECompanion\CompanionDataView.cs:line 164
   at IBE.IBECompanion.CompanioDataView.CompanioDataView_Load(Object sender, EventArgs e) in E:\dev\RN\ED-IBE\ED-IBE\IBECompanion\CompanionDataView.cs:line 36
--------------------------------------------------------------------------------
13.01.2019 00:39:21 : Error while getting data from the servers
13.01.2019 00:39:21 :    at IBE.IBECompanion.CompanionData.GetProfileData(Boolean useCachedData) in E:\dev\RN\ED-IBE\ED-IBE\IBECompanion\CompanionData.cs:line 231
   at IBE.IBECompanion.CompanioDataView.GetState() in E:\dev\RN\ED-IBE\ED-IBE\IBECompanion\CompanionDataView.cs:line 68

**Comment by Komak57** [comment]
Login service previously used is no longer in service. Trying to backtrack through the source to find out what it needs to function.

**Comment by Anaerin** [comment]
From the 404 error, it looks like whatever URL this was using to login to the ED Companion servers has gone away.
